version: '3.8'

services:
  # Laravel Backend
  qode_backend:
    build:
      context: qode_backend
    container_name: qode_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./qode_backend/.env:/var/www/.env
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8000:80"
    volumes:
      - ./qode_backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - qode_backend
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: robot@123
      MYSQL_DATABASE: qode_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: robot@123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network


  # VueJS Frontend
  qode_frontend:
    build:
      context: qode_frontend
    container_name: qode_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./qode_frontend:/usr/src/app
    networks:
      - app-network

  queue_worker:
    build:
      context: ./qode_backend
    container_name: qode_backend_worker
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    restart: unless-stopped
    depends_on:
      - qode_backend
      - db
    volumes:
      - ./qode_backend:/var/www
      - ./qode_backend/.env:/var/www/.env
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  elasticsearch_data: